###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:

    react-app:
        build: ./my_app
        ports:
            - "3000:3000"
    #memcached:
     #   image: 'memcached:alpine'

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '57001:8025'

    #redis:
     #   image: 'redis:alpine'

    postgres:
        image: 'postgres:15-alpine'
        working_dir: /application
        volumes:
            - './database:/application'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=teste21
            - POSTGRES_DB=postgres
        ports:
            - '57004:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '57000:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/cli/conf.d/99-overrides.ini'

    